# Generated by Django 5.0.7 on 2024-07-30 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AutorModel',
            new_name='Autor',
        ),
    ]
