# Generated by Django 5.0.7 on 2024-07-31 23:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrela', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Não pode ser menor que zero!'), django.core.validators.MaxValueValidator(5, 'Não pode ser maior que zero!')])),
                ('comentario', models.TextField(blank=True, null=True)),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avaliacao', to='filme.filme')),
            ],
        ),
    ]
